@echo off
mkdir "A Brief Frequency Analysis"
copy "pages\A+Brief+Frequency+Analysis.html" "A Brief Frequency Analysis\index.html"
mkdir "Algorithmic approaches - thoughts"
copy "pages\Algorithmic+approaches+-+thoughts.html" "Algorithmic approaches - thoughts\index.html"
mkdir "An examination of source material"
copy "pages\An+examination+of+source+material.html" "An examination of source material\index.html"
mkdir "An image based approach"
copy "pages\An+image+based+approach.html" "An image based approach\index.html"
mkdir "Andrew Browne"
copy "pages\Andrew+Browne.html" "Andrew Browne\index.html"
mkdir "Andrew Steer"
copy "pages\Andrew+Steer.html" "Andrew Steer\index.html"
mkdir "Andy O'Dwyer"
copy "pages\Andy+O'Dwyer.html" "Andy O'Dwyer\index.html"
mkdir "Build a database of dot-signatures"
copy "pages\Build+a+database+of+dot-signatures.html" "Build a database of dot-signatures\index.html"
mkdir "Chroma field Separation"
copy "pages\Chroma+field+Separation.html" "Chroma field Separation\index.html"
mkdir "Colour Quadrant Correction"
copy "pages\Colour+Quadrant+Correction.html" "Colour Quadrant Correction\index.html"
mkdir "Colour recovery - using existing material as a reference"
copy "pages\Colour+recovery+-+using+existing+material+as+a+reference.html" "Colour recovery - using existing material as a reference\index.html"
mkdir "Colour recovery - using virtual dub filters"
copy "pages\Colour+recovery+-+using+virtual+dub+filters.html" "Colour recovery - using virtual dub filters\index.html"
mkdir "Conversion of UYVY files to Y-only files"
copy "pages\Conversion+of+UYVY+files+to+Y-only+files.html" "Conversion of UYVY files to Y-only files\index.html"
mkdir "Current work"
copy "pages\Current+work.html" "Current work\index.html"
mkdir "Experiment in utilising the four frame sequence"
copy "pages\Experiment+in+utilising+the+four+frame+sequence.html" "Experiment in utilising the four frame sequence\index.html"
mkdir "Experiments in Geometric Correction"
copy "pages\Experiments+in+Geometric+Correction.html" "Experiments in Geometric Correction\index.html"
mkdir "Experiments in recreation of line-structure through  block-matching"
copy "pages\Experiments+in+recreation+of+line-structure+through++block-matching.html" "Experiments in recreation of line-structure through  block-matching\index.html"
mkdir "Extrapolating A More Complete Field Separation"
copy "pages\Extrapolating+A+More+Complete+Field+Separation.html" "Extrapolating A More Complete Field Separation\index.html"
mkdir "Full gamut colour recovery"
copy "pages\Full+gamut+colour+recovery.html" "Full gamut colour recovery\index.html"
mkdir "Full gamut colour recovery (continued)"
copy "pages\Full+gamut+colour+recovery+(continued).html" "Full gamut colour recovery (continued)\index.html"
mkdir "Full gamut colour recovery (yet more)"
copy "pages\Full+gamut+colour+recovery+(yet+more).html" "Full gamut colour recovery (yet more)\index.html"
mkdir "Future work"
copy "pages\Future+work.html" "Future work\index.html"
mkdir "General Requirements"
copy "pages\General+Requirements.html" "General Requirements\index.html"
mkdir "Geometric Correction (contd once more)"
copy "pages\Geometric+Correction+(contd+once+more).html" "Geometric Correction (contd once more)\index.html"
mkdir "Geometric Correction (contd)"
copy "pages\Geometric+Correction+(contd).html" "Geometric Correction (contd)\index.html"
mkdir "Geometric recovery - Through frequency analysis"
copy "pages\Geometric+recovery+-+Through+frequency+analysis.html" "Geometric recovery - Through frequency analysis\index.html"
mkdir "home"
copy "pages\home.html" "home\index.html"
mkdir "Investigations into intra-frame decoding"
copy "pages\Investigations+into+intra-frame+decoding.html" "Investigations into intra-frame decoding\index.html"
mkdir "James Insell"
copy "pages\James+Insell.html" "James Insell\index.html"
mkdir "Jim Easterbrook"
copy "pages\Jim+Easterbrook.html" "Jim Easterbrook\index.html"
mkdir "Members"
copy "pages\Members.html" "Members\index.html"
mkdir "Michael Firth"
copy "pages\Michael+Firth.html" "Michael Firth\index.html"
mkdir "PhilipG"
copy "pages\PhilipG.html" "PhilipG\index.html"
mkdir "Previous work"
copy "pages\Previous+work.html" "Previous work\index.html"
mkdir "Reversal of geometrical distortion through block-matching against an existing video reference"
copy "pages\Reversal+of+geometrical+distortion+through+block-matching+against+an+existing+video+reference.html" "Reversal of geometrical distortion through block-matching against an existing video reference\index.html"
mkdir "Richard Russell's experiments"
copy "pages\Richard+Russell's+experiments.html" "Richard Russell's experiments\index.html"
mkdir "Separating the Fields"
copy "pages\Separating+the+Fields.html" "Separating the Fields\index.html"
mkdir "Separating the Fields and Geometric Correction (contd)"
copy "pages\Separating+the+Fields+and+Geometric+Correction+(contd).html" "Separating the Fields and Geometric Correction (contd)\index.html"
mkdir "Single-frame decoding continued"
copy "pages\Single-frame+decoding+continued.html" "Single-frame decoding continued\index.html"
mkdir "space.menu"
copy "pages\space.menu.html" "space.menu\index.html"
mkdir "SteveB"
copy "pages\SteveB.html" "SteveB\index.html"
mkdir "Towards full-gamut"
copy "pages\Towards+full-gamut.html" "Towards full-gamut\index.html"
mkdir "Undistorting Image Sequences"
copy "pages\Undistorting+Image+Sequences.html" "Undistorting Image Sequences\index.html"
mkdir "Updates"
copy "pages\Updates.html" "Updates\index.html"
mkdir "Use the mathematical relationship between the chroma signals in successive frames to recover geometry and colour information"
copy "pages\Use+the+mathematical+relationship+between+the+chroma+signals+in+successive+frames+to+recover+geometry+and+colour+information.html" "Use the mathematical relationship between the chroma signals in successive frames to recover geometry and colour information\index.html"
mkdir "Utilities"
copy "pages\Utilities.html" "Utilities\index.html"
pause